/**
 * 
 */
define(["bcnew/bcnewAsset"],
function(bcnewAsset) {
	
	var mainCfg = {
	    "name":"Texture",
	    "rendererCfg":{
	        "image":"nbg",
	        "sprite":""
	    },
	    "colliderCfg":{
	        "bound":{
	            "serializedVersion":"2",
	            "x":0,
	            "y":0,
	            "width":0,
	            "height":0
	        },
	        "offset":{
	            "x":0,
	            "y":0
	        }
	    },
	    "transformCfg":{
	        "depth":0,
	        "localPos":{
	            "x":-360,
	            "y":568
	        },
	        "localSize":{
	            "x":720,
	            "y":1136
	        },
	        "localScale":{
	            "x":1,
	            "y":1
	        }
	    },
	    "children":[
	        {
	            "name":"path",
	            "rendererCfg":{
	                "image":"",
	                "sprite":""
	            },
	            "colliderCfg":{
	                "bound":{
	                    "serializedVersion":"2",
	                    "x":0,
	                    "y":0,
	                    "width":0,
	                    "height":0
	                },
	                "offset":{
	                    "x":0,
	                    "y":0
	                }
	            },
	            "transformCfg":{
	                "depth":0,
	                "localPos":{
	                    "x":360,
	                    "y":-568
	                },
	                "localSize":{
	                    "x":1,
	                    "y":1
	                },
	                "localScale":{
	                    "x":1,
	                    "y":1
	                }
	            },
	            "children":[
	                {
	                    "name":"0",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":108,
	                            "y":238
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"1",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-2,
	                            "y":238
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"2",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-112,
	                            "y":238
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"3",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-222,
	                            "y":238
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"4",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-222,
	                            "y":128
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"5",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-332,
	                            "y":128
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"6",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-332,
	                            "y":17
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"7",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-332,
	                            "y":-93
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"8",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-332,
	                            "y":-203
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"9",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-332,
	                            "y":-313
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"10",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-222,
	                            "y":-313
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"11",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-222,
	                            "y":-423
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"12",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-112,
	                            "y":-423
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"13",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":-2,
	                            "y":-423
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"14",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":108,
	                            "y":-423
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"15",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":108,
	                            "y":-313
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"16",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":218,
	                            "y":-313
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"17",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":218,
	                            "y":-203
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"18",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":218,
	                            "y":-93
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"19",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":218,
	                            "y":17
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"20",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":218,
	                            "y":128
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                },
	                {
	                    "name":"21",
	                    "rendererCfg":{
	                        "image":"main",
	                        "sprite":"kuang_empty"
	                    },
	                    "colliderCfg":{
	                        "bound":{
	                            "serializedVersion":"2",
	                            "x":0,
	                            "y":0,
	                            "width":0,
	                            "height":0
	                        },
	                        "offset":{
	                            "x":0,
	                            "y":0
	                        }
	                    },
	                    "transformCfg":{
	                        "depth":0,
	                        "localPos":{
	                            "x":108,
	                            "y":128
	                        },
	                        "localSize":{
	                            "x":102,
	                            "y":102
	                        },
	                        "localScale":{
	                            "x":1,
	                            "y":1
	                        }
	                    },
	                    "children":[

	                    ]
	                }
	            ]
	        },
	        {
	            "name":"dice",
	            "rendererCfg":{
	                "image":"main",
	                "sprite":"shaizi_01"
	            },
	            "colliderCfg":{
	                "bound":{
	                    "serializedVersion":"2",
	                    "x":0,
	                    "y":0,
	                    "width":0,
	                    "height":0
	                },
	                "offset":{
	                    "x":0,
	                    "y":0
	                }
	            },
	            "transformCfg":{
	                "depth":0,
	                "localPos":{
	                    "x":307,
	                    "y":-839
	                },
	                "localSize":{
	                    "x":106,
	                    "y":118
	                },
	                "localScale":{
	                    "x":1,
	                    "y":1
	                }
	            },
	            "children":[

	            ]
	        },
	        {
	            "name":"dog",
	            "rendererCfg":{
	                "image":"main",
	                "sprite":"dog_icon"
	            },
	            "colliderCfg":{
	                "bound":{
	                    "serializedVersion":"2",
	                    "x":0,
	                    "y":0,
	                    "width":0,
	                    "height":0
	                },
	                "offset":{
	                    "x":0,
	                    "y":0
	                }
	            },
	            "transformCfg":{
	                "depth":0,
	                "localPos":{
	                    "x":450,
	                    "y":-236.99996948242187
	                },
	                "localSize":{
	                    "x":128,
	                    "y":174
	                },
	                "localScale":{
	                    "x":1,
	                    "y":1
	                }
	            },
	            "children":[

	            ]
	        }
	    ]
	}
	
	
})